title: CLS Genomics data
description: This site provides all the details about the CLS genomic data 
theme: just-the-docs

# External navigation links
nav_external_links:
  - title: CLS Genomics data
    url: https://cls-genetics.github.io/docs/intro.html
    hide_icon: false # set to true to hide the external link icon - defaults to false
