title: CLS Genomic data
description: This site provides all the details about the CLS genomic data 
theme: just-the-docs

url: https://github.com/CLS-Genetics/cls-genetics.github.io/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/CLS-Genetics/cls-genetics.github.io/
