title: "CLS Genomics Data"
description: "This site provides documentation for the CLS genomic data."
theme: just-the-docs

# If your site is served at https://cls-genetics.github.io/ (no extra repo path), leave baseurl blank:
url: "https://cls-genetics.github.io"
baseurl: ""

# Any extra links in the top-right corner, for example:
aux_links:
  "CLS Genomics on GitHub": "https://github.com/cls-genetics"

# Enable Just the Docs search bar
search_enabled: true

# Optionally set color scheme (light or dark)
color_scheme: light

# Point to a favicon if you have one:
favicon_ico: "/assets/images/favicon.ico"

# Plugins you want. Here jekyll-seo-tag is common:
plugins:
  - jekyll-seo-tag
