title: CLS Genomics Data
description: This site provides all the details about the CLS genomic data 
theme: just-the-docs

# For local development
# theme: just-the-docs

# For GitHub Pages deployment
# remote_theme: just-the-docs/just-the-docs

url: https://cls-genetics.github.io
baseurl: ""  # the subpath of your site, e.g. /blog

# Aux links for the upper right navigation
aux_links:
  "CLS Genomics on GitHub":
    - "https://github.com/cls-genetics"

# Enable search
search_enabled: true

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the site search
search_enabled: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light